CREATE TABLE IF NOT EXISTS panier (
    id NUMERIC PRIMARY KEY,
    id_ligne_panier INTEGER NOT NULL,
    montant_tcc INTEGER NOT NULL,
    who_done VARCHAR(64) NOT NULL DEFAULT CURRENT_USER,
    when_done TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);